import { useEffect, useMemo, useRef, useState } from 'react'

const pdfTools = [
  { icon:'✎', name:'Chỉnh sửa PDF', description:'Thêm văn bản, hình ảnh, ký tên, ghi chú...', color:'coral', mode:'soon' },
  { icon:'✳', name:'Nén PDF', description:'Giảm dung lượng file PDF mà không giảm chất lượng', color:'red', mode:'pdf-compress' },
  { icon:'W', name:'PDF sang Word', description:'Chuyển đổi PDF sang file Word dễ dàng', color:'blue', mode:'soon' },
  { icon:'X', name:'PDF sang Excel', description:'Chuyển đổi PDF sang file Excel', color:'green', mode:'soon' },
  { icon:'P', name:'PDF sang PowerPoint', description:'Chuyển đổi PDF sang file PowerPoint', color:'orange', mode:'soon' },
  { icon:'◫', name:'Cắt PDF', description:'Cắt file PDF theo trang mong muốn', color:'purple', mode:'pdf-split' },
]
const imageTools = [
  { icon:'♙', name:'Xóa phông nền', description:'Tự động xóa phông nền ảnh chỉ với 1 click', color:'blue', mode:'remove-background' },
  { icon:'▣', name:'Chuyển đổi định dạng', description:'Chuyển đổi JPG, PNG, WEBP, BMP và nhiều định dạng khác', color:'teal', mode:'convert' },
  { icon:'⛶', name:'Thay đổi kích thước', description:'Thay đổi kích thước ảnh nhanh chóng', color:'violet', mode:'resize' },
  { icon:'⌗', name:'Cắt ảnh', description:'Cắt ảnh theo kích thước hoặc tỉ lệ tùy chỉnh', color:'pink', mode:'crop' },
  { icon:'✳', name:'Nén ảnh', description:'Giảm dung lượng ảnh mà không giảm chất lượng', color:'yellow', mode:'compress' },
  { icon:'☷', name:'Chỉnh sửa ảnh', description:'Điều chỉnh màu sắc, độ sáng, tương phản và hơn thế nữa', color:'indigo', mode:'soon' },
]
const labels = { 'pdf-compress':'Nén PDF', 'pdf-merge':'Ghép PDF', 'pdf-split':'Cắt PDF', compress:'Nén ảnh', convert:'Chuyển đổi định dạng ảnh', resize:'Thay đổi kích thước', crop:'Cắt ảnh', 'remove-background':'Xóa phông nền' }
const imageModes = ['compress','convert','resize','crop','remove-background']

function ToolCard({ tool, open }) { return <button className="tool-card" onClick={() => open(tool.mode)}><span className={`tool-icon ${tool.color}`}>{tool.icon}</span><strong>{tool.name}</strong><small>{tool.description}</small></button> }
function ToolSection({ title, tools, id, open, query }) { const visible = tools.filter(t => `${t.name} ${t.description}`.toLowerCase().includes(query.toLowerCase())); return <section className="tool-section" id={id}><div className="section-heading"><h2>{title}</h2><a href={`#${id}`}>Xem tất cả {id === 'pdf' ? 'PDF Tools' : 'Image Tools'} <span>→</span></a></div><div className="tools-grid">{visible.map(tool => <ToolCard key={tool.name} tool={tool} open={open}/>)}</div>{!visible.length && <p className="empty">Chưa tìm thấy công cụ phù hợp.</p>}</section> }

function ToolModal({ mode, close }) {
  const [files,setFiles] = useState([]), [format,setFormat] = useState('webp'), [quality,setQuality] = useState(82), [width,setWidth] = useState(''), [height,setHeight] = useState(''), [cropWidth,setCropWidth] = useState(''), [cropHeight,setCropHeight] = useState(''), [backgroundQuality,setBackgroundQuality] = useState('balanced'), [previewUrl,setPreviewUrl] = useState(''), [loading,setLoading] = useState(false), [message,setMessage] = useState('')
  const input = useRef(null), isImage = imageModes.includes(mode), isMerge = mode === 'pdf-merge', fileAccept = mode === 'remove-background' ? '.png,.jpg,.jpeg,.webp' : isImage ? 'image/*' : '.pdf,application/pdf'
  if (mode === 'soon') return <div className="modal-shade"><div className="tool-modal intro"><button className="close" onClick={close}>×</button><i>✦</i><h2>Tính năng đang hoàn thiện</h2><p>Những công cụ cần chuyển đổi tài liệu có cấu trúc phức tạp sẽ sớm được phát hành. Các công cụ ảnh và PDF khác đã hoạt động.</p><button className="primary" onClick={close}>Khám phá công cụ khác</button></div></div>
  const choose = selected => { setFiles(Array.from(selected || [])); setMessage(''); setPreviewUrl('') }
  const download = (blob, name) => { const objectUrl = URL.createObjectURL(blob), link = document.createElement('a'); link.href = objectUrl; link.download = name; link.click(); URL.revokeObjectURL(objectUrl) }
  const submit = async event => { event.preventDefault(); if (!files.length) return setMessage('Hãy chọn tệp trước khi xử lý.'); setLoading(true); setMessage(''); try { if (mode === 'remove-background') { setMessage('Đang chuẩn bị AI xóa phông…'); const { removeBackground } = await import('@imgly/background-removal'); const options = { model: backgroundQuality === 'high' ? 'isnet_fp16' : 'isnet_quint8', output: { format: 'image/png', quality: .95, type: 'foreground' }, progress: (_key, current, total) => { if (total) setMessage(`Đang tải mô hình AI: ${Math.round(current / total * 100)}%…`) } }; const run = device => removeBackground(files[0], { ...options, device }); let blob; try { blob = await run(globalThis.navigator?.gpu ? 'gpu' : 'cpu') } catch (gpuError) { if (!globalThis.navigator?.gpu) throw gpuError; setMessage('GPU không khả dụng, đang chuyển sang CPU…'); blob = await run('cpu') } setPreviewUrl(URL.createObjectURL(blob)); download(blob, `${files[0].name.replace(/\.[^/.]+$/, '')}-no-background.png`); setMessage('Xóa phông hoàn tất — xem trước kết quả bên dưới hoặc dùng tệp PNG đã tải xuống.'); return } const form = new FormData(); isMerge ? files.forEach(f => form.append('files',f)) : form.append('file',files[0]); if (isImage) Object.entries({format,quality,width,height,cropWidth,cropHeight,left:0,top:0}).forEach(([key,value]) => form.append(key,value)); const url = isImage ? `/api/tools/image/${mode}` : `/api/tools/pdf/${mode.replace('pdf-','')}`; const response = await fetch(url,{method:'POST',body:form}); if (!response.ok) throw new Error((await response.json().catch(()=>({}))).message || 'Không thể xử lý tệp.'); const blob = await response.blob(), header = response.headers.get('content-disposition') || ''; download(blob, /filename="?([^";]+)"?/.exec(header)?.[1] || 'toolhub-result'); setMessage('Xử lý hoàn tất — tệp đã được tải xuống!') } catch(error) { setMessage(error.message || 'Không thể xóa phông. Hãy thử lại bằng ảnh JPG hoặc PNG.') } finally { setLoading(false) } }
  return <div className="modal-shade" role="dialog" aria-modal="true"><form className="tool-modal" onSubmit={submit}><button className="close" type="button" onClick={close}>×</button><div className="modal-heading"><i>✦</i><div><p>CÔNG CỤ PDFTOOLS</p><h2>{labels[mode]}</h2></div></div><p className="modal-copy">{isMerge?'Chọn các tệp PDF theo thứ tự muốn ghép.':mode==='remove-background'?'AI sẽ tách chủ thể khỏi nền ngay trên thiết bị của bạn. Hỗ trợ JPG, PNG, WebP; lần đầu cần tải mô hình khoảng 40 MB.':'Tệp được xử lý an toàn và tự tải xuống khi hoàn tất.'}</p><div className="drop-zone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files)}}><input ref={input} hidden type="file" accept={fileAccept} multiple={isMerge} onChange={e=>choose(e.target.files)}/><span>⇧</span><b>{files.length?`${files.length} tệp đã chọn`:`Kéo thả ${isMerge?'các tệp':'tệp'} vào đây`}</b><small>{files.length?files.map(f=>f.name).join(', '):'hoặc nhấp để chọn từ máy tính'}</small></div>{mode==='remove-background'&&<div className="background-settings"><span>Chế độ xóa phông</span><div><button type="button" className={backgroundQuality==='balanced'?'active':''} onClick={()=>setBackgroundQuality('balanced')}><b>Nhanh</b><small>~40 MB, phù hợp ảnh thông thường</small></button><button type="button" className={backgroundQuality==='high'?'active':''} onClick={()=>setBackgroundQuality('high')}><b>Chất lượng cao</b><small>~80 MB, viền tóc tốt hơn</small></button></div></div>}{isImage&&mode!=='remove-background'&&<div className="settings"><label>Định dạng<select value={format} onChange={e=>setFormat(e.target.value)}><option value="webp">WebP</option><option value="jpeg">JPG</option><option value="png">PNG</option><option value="avif">AVIF</option></select></label>{mode!=='crop'&&<label>Chất lượng <b>{quality}%</b><input type="range" min="20" max="100" value={quality} onChange={e=>setQuality(e.target.value)}/></label>}{mode==='resize'&&<div className="dimensions"><label>Rộng (px)<input value={width} onChange={e=>setWidth(e.target.value)} placeholder="Tự động"/></label><label>Cao (px)<input value={height} onChange={e=>setHeight(e.target.value)} placeholder="Tự động"/></label></div>}{mode==='crop'&&<div className="dimensions"><label>Rộng (px)<input value={cropWidth} onChange={e=>setCropWidth(e.target.value)} placeholder="Toàn bộ"/></label><label>Cao (px)<input value={cropHeight} onChange={e=>setCropHeight(e.target.value)} placeholder="Toàn bộ"/></label></div>}</div>}<button className="primary process" disabled={loading}>{loading?'Đang xử lý…':'Xử lý và tải xuống  →'}</button>{message&&<p className={`result ${message.includes('hoàn tất')?'success':''}`}>{message}</p>}{previewUrl&&<div className="background-preview"><span>Xem trước nền trong suốt</span><img src={previewUrl} alt="Kết quả xóa phông"/></div>}</form></div>
}

export default function App() {
  const [dark,setDark] = useState(()=>localStorage.getItem('pdftools-theme')==='dark'), [modal,setModal] = useState(null), [query,setQuery] = useState(''), [mail,setMail] = useState('')
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('pdftools-theme',dark?'dark':'light')},[dark])
  const count = useMemo(()=>[...pdfTools,...imageTools].filter(t=>t.name.toLowerCase().includes(query.toLowerCase())).length,[query])
  const subscribe = async e => { e.preventDefault(); const email=new FormData(e.currentTarget).get('email'); await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})}).catch(()=>null); setMail('Đăng ký thành công!') }
  return <div className="app redesigned"><header className="header"><a className="brand" href="#home"><span>P</span>PDFTools</a><nav><a className="active" href="#home">Trang chủ</a><a href="#pdf">PDF Tools　⌄</a><a href="#images">Image Tools　⌄</a><a href="#pricing">Giá cả</a><a href="#blog">Blog</a></nav><div className="header-actions"><button className="theme-toggle" aria-label="Đổi chế độ màu" onClick={()=>setDark(!dark)}>{dark?'☀':'☼'}</button><button className="language">◎　VI　⌄</button><button className="login">Đăng nhập</button></div></header><main id="home"><section className="hero"><div className="hero-copy"><h1>Tất cả công cụ<br/><em>PDF &amp; Ảnh</em> miễn phí</h1><p className="hero-text">Chỉnh sửa, chuyển đổi, nén PDF và xử lý hình ảnh<br/>đa dạng, nhanh chóng và bảo mật.</p><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm kiếm công cụ bạn cần..."/><small>{query&&`${count} công cụ`}</small></label></div><div className="hero-illustration"><div className="document"><div className="doc-dots">●　●　●</div><div className="doc-sidebar"></div><div className="doc-lines"><b></b><b></b><b></b><b></b><div></div><b></b></div></div><span className="hero-chip pdf">♧</span><span className="hero-chip word">W</span><span className="hero-chip image">▣</span><span className="hero-chip add">＋</span><i className="spark s1">✦</i><i className="spark s2">✦</i></div></section><div className="content"><ToolSection title="Công cụ PDF" tools={pdfTools} id="pdf" open={setModal} query={query}/><ToolSection title="Công cụ Ảnh" tools={imageTools} id="images" open={setModal} query={query}/><section className="benefits"><Benefit icon="♢" title="Bảo mật tuyệt đối" text="File của bạn được xử lý an toàn và tự động xóa sau 1 giờ."/><Benefit icon="ϟ" title="Xử lý nhanh chóng" text="Công nghệ hiện đại giúp xử lý file trong tích tắc."/><Benefit icon="☁" title="Hỗ trợ mọi thiết bị" text="Sử dụng dễ dàng trên mọi thiết bị, mọi nền tảng."/><Benefit icon="✪" title="Hoàn toàn miễn phí" text="Nhiều công cụ miễn phí 100%, không giới hạn lượt sử dụng."/></section></div></main><footer><div className="footer-top"><div className="footer-brand"><a className="brand" href="#home"><span>P</span>PDFTools</a><p>Một nơi đơn giản để xử lý mọi tài liệu và hình ảnh của bạn.</p></div><Footer title="Sản phẩm" items={['PDF Tools','Image Tools','Công cụ khác']}/><Footer title="Công ty" items={['Giới thiệu','Blog','Liên hệ']}/><div className="newsletter"><p>NHẬN MẸO HAY MỖI TUẦN</p><h3>Không bỏ lỡ điều thú vị</h3><form onSubmit={subscribe}><input name="email" required type="email" placeholder="Email của bạn"/><button>→</button></form>{mail&&<small>{mail}</small>}</div></div><p className="copyright">© 2026 PDFTools · Làm việc thông minh hơn, mỗi ngày.</p></footer>{modal&&<ToolModal mode={modal} close={()=>setModal(null)}/>}</div>
}
function Benefit({icon,title,text}) { return <div><i>{icon}</i><span><strong>{title}</strong><small>{text}</small></span></div> }
function Footer({title,items}) { return <div className="footer-column"><h3>{title}</h3>{items.map(item=><a href="#home" key={item}>{item}</a>)}</div> }
